repos:
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args:
        - --config=.hooks/.flake8
-   repo: https://github.com/pycqa/pylint
    rev: v2.13.7
    hooks:
    - id: pylint
      args:
      - --rcfile=.hooks/.pylintrc
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      args:
          - --config
          - .hooks/black.toml
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
    -   id: mypy
        args:
          - --config-file=.hooks/mypy.ini
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --settings-file=.hooks/isort.toml